### ISSUE TITLE
Size error with ACT DR4

### ISSUE THREAD

**Issue by zonca** [simonsobs/tilemaker#1]
Tried to run the example with `ACTPol_148_D5_PA1_S1_1way_I.fits` from [https://lambda.gsfc.nasa.gov/product/act/actpol_maps_get.html](https://urldefense.com/v3/__https://lambda.gsfc.nasa.gov/product/act/actpol_maps_get.html__;!!Mih3wA!ApHAdcgcc8xFOx6luhID2SdO3g0-qSa-Fph_2BXzCj5DalLicivbogpoiWziQZ_pky_mD-sLE-Fz1sO5VIw$)

I get an error in the shape of the arrays:

```
python fits.py create ACTPol_148_D5_PA1_S1_1way_I.fits ACTPol_148_D5_PA1_S1_1w
ay_I
Traceback (most recent call last):
  File "/home/zonca/p/software/tilemaker/example/fits.py", line 48, in <module>
    tree = LayerTree(number_of_layers=number_of_layers, image_pixel_size=tile_size, image=fits_image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zonca/p/software/tilemaker/tilemaker/processing/fits_simple.py", line 422, in __init__
    layer.create_data_from_children()
  File "/home/zonca/p/software/tilemaker/tilemaker/processing/fits_simple.py", line 382, in create_data_from_children
    node.create_data_from_children()
  File "/home/zonca/p/software/tilemaker/tilemaker/processing/fits_simple.py", line 310, in create_data_from_children
    data_buffer[covered_region] = 0.25 * child_data
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (667,675) into shape (674,675)
```

**Comment by JBorrow** [comment]
Oh no, that really shouldn't happen! I will look into this tomorrow, can you progress using the (admittedly larger) DR5 data for now?

**Comment by zonca** [comment]
yes, I had to use NERSC to create the DB, 6 GB RAM on my laptop were not enough, but now works fine.

**Comment by JBorrow** [comment]
Looks like this originates from the DR4 maps not being full-sky. I had thought that pixell always returned a full array when reading off the edge of the map with WCS, and it turns out it doesn't. Will need to fix that (there is some code to do this already within the other FITS backend).
